# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"normalize": "data.ipynb",
         "trunc_norm": "data.ipynb",
         "Compose": "data.ipynb",
         "Random": "data.ipynb",
         "ToTensor": "data.ipynb",
         "Normalize": "data.ipynb",
         "Resize": "data.ipynb",
         "Blur": "data.ipynb",
         "RandomBlur": "data.ipynb",
         "Contrast": "data.ipynb",
         "RandomContrast": "data.ipynb",
         "Brightness": "data.ipynb",
         "RandomBrightness": "data.ipynb",
         "Grad": "data.ipynb",
         "RandomGrad": "data.ipynb",
         "Clip": "data.ipynb",
         "Noise": "data.ipynb",
         "IsliceDataloader": "data.ipynb",
         "SyntheticMaskDataSet": "data.ipynb",
         "RealMaskDataSet": "data.ipynb",
         "meshgrid2ps": "gen_cb.ipynb",
         "affine_ps": "gen_cb.ipynb",
         "homography_ps": "gen_cb.ipynb",
         "rotate_ps": "gen_cb.ipynb",
         "get_circle_poly": "gen_cb.ipynb",
         "rotate_poly": "gen_cb.ipynb",
         "affine_poly": "gen_cb.ipynb",
         "poly2coords": "gen_cb.ipynb",
         "affine_coords": "gen_cb.ipynb",
         "homography_coords": "gen_cb.ipynb",
         "plot_coords": "gen_cb.ipynb",
         "euler2R": "gen_cb.ipynb",
         "ARt2H": "gen_cb.ipynb",
         "get_bb": "gen_cb.ipynb",
         "get_fiducial_poly": "gen_cb.ipynb",
         "get_checker_poly": "gen_cb.ipynb",
         "get_ps_b": "gen_cb.ipynb",
         "get_ps_fp": "gen_cb.ipynb",
         "get_ps_t": "gen_cb.ipynb",
         "get_poly_cb": "gen_cb.ipynb",
         "plot_cb_poly": "gen_cb.ipynb",
         "draw_ps": "gen_cb.ipynb",
         "draw_coords": "gen_cb.ipynb",
         "get_out_channels": "models.ipynb",
         "conv_layer": "models.ipynb",
         "up_conv_layer": "models.ipynb",
         "get_encoder": "models.ipynb",
         "UNET": "models.ipynb"}

modules = ["data.py",
           "gen_cb.py",
           "models.py"]

doc_url = "https://justinblaber.github.io/fiducial_detect/"

git_url = "https://github.com/justinblaber/fiducial_detect/tree/master/"

def custom_doc_links(name): return None